repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-xml
    -   id: end-of-file-fixer
        exclude: ^(src/uic/|src/translations/|src/includes/|src/test/data/|src/test/sanity/data/)
    -   id: trailing-whitespace
        exclude: ^(src/uic/|src/translations/|src/includes/|src/test/data/|src/test/sanity/data/)
    -   id: double-quote-string-fixer
        exclude: ^(src/uic/|src/translations/|src/includes/|src/test/data/|src/test/sanity/data/)
    -   id: check-ast
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
        exclude: ^(src/uic/|src/translations/|src/includes/)
-   repo: local
    hooks:
      - id: update-artisan-signature
        name: Update Artisan Signature
        entry: python src/run_signature.py
        language: system
        files: ^src/artisanlib/__init__.py$
        stages: [pre-commit]
        pass_filenames: false
